name: CI

on:
  push:
    branches:
      - "*"

jobs:
  main:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Show env
        run: env | sort

      - name: Show go location
        run: which go

      - name: Install binary
        run: make install